Repository tjmelo/tmx-moon, pull requests merged in 2024-02, with the labels that each got.

#48 Improving actions on app
  .env
  .github/workflows/checkout-ci.yml
  .github/workflows/image-ci.yml
  .github/workflows/release-ci.yml
  compose.yml
Labels: enhancement

#49 Updating version app
  package-lock.json
  package.json
Labels: enhancement

#52 fix: fixing ci
  .github/workflows/release-ci.yml
Labels: bug

#54 fix: removing unnecessary action
  .github/workflows/release-ci.yml
Labels: bug

#57 Update axios version
  package-lock.json
  package.json
  yarn.lock
Labels: dependencies
